name: AI PR Review with Python and Qdrant

on:
  #workflow_dispatch:  # Manually trigger the action
  pull_request:
    types: [ready_for_review]

jobs:
  review-with-ai:
    # Allow only when the user is sasakisasaki
    if: github.event.pull_request.user.login == 'sasakisasaki'
    runs-on: ubuntu-latest

    services:
      qdrant:
        image: j2sasaki/qdrant-with-data
        ports:
          - 6333:6333

    env:
      COMMIT_SHA: ${{ github.event.pull_request.head.sha || 'dummy-sha-for-manual-trigger' }}
      REPO_OWNER: ${{ github.repository_owner }}
      REPO_NAME: ${{ github.event.repository.name || github.repository }}
      PR_INDEX: ${{ github.event.pull_request.number || '0' }}
      QDRANT_HOST: localhost
      QDRANT_PORT: 6333
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

    steps:
      - name: Generate GitHub App token
        id: token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.base_ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          pip install -r ${GITHUB_WORKSPACE}/.github/scripts/requirements.txt || echo "No requirements.txt found, skipping."

      - name: Fetch base branch and generate git diff
        run: |
          git fetch origin ${{ github.base_ref }}
          git diff origin/${{ github.base_ref }}... > pr_diff.patch
          cat pr_diff.patch

      - name: Run Python script
        run: |
          export PYTHONPATH="${GITHUB_WORKSPACE}/.github/scripts"
          python .github/scripts/do_chunk_review.py --diff_file pr_diff.patch
